### ISSUE TITLE
Android keyboard shrinks the employment verification modal

### ISSUE THREAD

**Issue by chittolina** [citadelid/quickstart#33]
Hey guys. Not sure if this is the best channel to ask for help, but we're having this issue w/ Android devices. When the keyboard is open apparently the viewport shrinks and the page gets all huddled. We reproduced the issue on our app (where we load citadel bridge inside a webview) but I managed to reproduce it also here on the quickstart.

![Screen Shot 2021-06-15 at 3 49 27 PM](https://user-images.githubusercontent.com/12752712/122108073-2d41d180-cdf2-11eb-8ee9-65a252e8041e.png)

Any help would be much appreciated, thank you!

**Comment by rjriel** [comment]
Hi @chittolina,

Can you let me know your device details you're testing on?

**Comment by chittolina** [comment]
@rjriel I reproduced that issue in both Chrome (using Nexus as you can see in the screenshot) but also reproduced on physical Pixel 3. I'm pretty sure that would happen in more devices too. I found some stuff in [StackOverflow](https://stackoverflow.com/questions/32963400/android-keyboard-shrinking-the-viewport-and-elements-using-unit-vh-in-css), might be useful.

**Comment by Laplandia** [comment]
Hi @chittolina,
we made changes to account for screen height change in this case. Did it solve the problem?

**Comment by chittolina** [comment]
Nice. I tested in the emulator and it worked just fine. Will ask our QA to test it on a physical device too. 

Thanks @Laplandia @rjriel

**Comment by chittolina** [comment]
All good. Closing the issue. Thanks everyone
